server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://crypto.climkdbihu7b.us-east-1.rds.amazonaws.com:3306/crypto
    username: root
    password: root12345
  jpa:
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect