server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crypto //replace your endpoint and port
    username: root
    password: root12345
  jpa:
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect